### ISSUE TITLE
Reference to 'tabs' in Other section is incorrect

### ISSUE THREAD

**Issue by benjamineskola** [chaselambda/vimsheet#21]
The Other section includes:

> - `:qa` - Quit all open tabs (thanks Vince Banzon)
> - `:wa` - Write all open tabs (thanks Vince Banzon)
> - `:wqa` - Write and quit all open tabs (thanks Brian Zick)

However that's inaccurate. All of these act on _buffers_, not tabs; tabs are not the same as buffers in Vim, [`:help tabpage`](http://vimdoc.sourceforge.net/htmldoc/tabpage.html).

**Comment by chaselambda** [comment]
Oops thank you, fixed!
