### ISSUE TITLE
Farsi/Persian Translation

### ISSUE THREAD

**Issue by amirofski** [chaselambda/vimsheet#24]
Hello Dear @theicfire ,
I hope everything is going well with you,
If you have a plan to make a multilanguage vimsheet, please let me know to make this part
Thanks

**Comment by chaselambda** [comment]
Thanks, I appreciate the interest!

**Comment by amirofski** [comment]
Thank you🙏. i make a fork and start

**Comment by chaselambda** [comment]
Oh sorry for clarification I won't be incorporating this for now, I don't
quite have the time
