### ISSUE TITLE
some typos in the webpage

### ISSUE THREAD

**Issue by Z-Y00** [chaselambda/vimsheet#6]
![image](https://user-images.githubusercontent.com/23717414/39184063-a2cf5e42-47b1-11e8-9102-6d3309284b35.png)

##General failed to display correctly, you can modify the markdown file in your repo.
you've just forgotten to add a space
just 
## General

**Comment by Z-Y00** [comment]
if you are just too busy, I'll launch a pull request. for there are already several pull request in your repo

**Comment by ahangarha** [comment]
Please merge these PRs. @theicfire 

Is there any way we can help?

**Comment by chaselambda** [comment]
Thanks! I've made the changes -- your PR had conflicts so I copied over the diff manually
